/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiGenerateLogoRouteImport } from './routes/api/generate-logo'
import { Route as ApiDownloadLogoRouteImport } from './routes/api/download-logo'
import { Route as ApiCheckoutConfirmRouteImport } from './routes/api/checkout-confirm'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiAnalyzeBriefRouteImport } from './routes/api/analyze-brief'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateLogoRoute = ApiGenerateLogoRouteImport.update({
  id: '/api/generate-logo',
  path: '/api/generate-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadLogoRoute = ApiDownloadLogoRouteImport.update({
  id: '/api/download-logo',
  path: '/api/download-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutConfirmRoute = ApiCheckoutConfirmRouteImport.update({
  id: '/api/checkout-confirm',
  path: '/api/checkout-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeBriefRoute = ApiAnalyzeBriefRouteImport.update({
  id: '/api/analyze-brief',
  path: '/api/analyze-brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/api/analyze-brief': typeof ApiAnalyzeBriefRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/checkout-confirm': typeof ApiCheckoutConfirmRoute
  '/api/download-logo': typeof ApiDownloadLogoRoute
  '/api/generate-logo': typeof ApiGenerateLogoRoute
  '/api/track': typeof ApiTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/api/analyze-brief': typeof ApiAnalyzeBriefRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/checkout-confirm': typeof ApiCheckoutConfirmRoute
  '/api/download-logo': typeof ApiDownloadLogoRoute
  '/api/generate-logo': typeof ApiGenerateLogoRoute
  '/api/track': typeof ApiTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/api/analyze-brief': typeof ApiAnalyzeBriefRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/checkout-confirm': typeof ApiCheckoutConfirmRoute
  '/api/download-logo': typeof ApiDownloadLogoRoute
  '/api/generate-logo': typeof ApiGenerateLogoRoute
  '/api/track': typeof ApiTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/api/analyze-brief'
    | '/api/checkout'
    | '/api/checkout-confirm'
    | '/api/download-logo'
    | '/api/generate-logo'
    | '/api/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/api/analyze-brief'
    | '/api/checkout'
    | '/api/checkout-confirm'
    | '/api/download-logo'
    | '/api/generate-logo'
    | '/api/track'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/api/analyze-brief'
    | '/api/checkout'
    | '/api/checkout-confirm'
    | '/api/download-logo'
    | '/api/generate-logo'
    | '/api/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiAnalyzeBriefRoute: typeof ApiAnalyzeBriefRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiCheckoutConfirmRoute: typeof ApiCheckoutConfirmRoute
  ApiDownloadLogoRoute: typeof ApiDownloadLogoRoute
  ApiGenerateLogoRoute: typeof ApiGenerateLogoRoute
  ApiTrackRoute: typeof ApiTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-logo': {
      id: '/api/generate-logo'
      path: '/api/generate-logo'
      fullPath: '/api/generate-logo'
      preLoaderRoute: typeof ApiGenerateLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-logo': {
      id: '/api/download-logo'
      path: '/api/download-logo'
      fullPath: '/api/download-logo'
      preLoaderRoute: typeof ApiDownloadLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout-confirm': {
      id: '/api/checkout-confirm'
      path: '/api/checkout-confirm'
      fullPath: '/api/checkout-confirm'
      preLoaderRoute: typeof ApiCheckoutConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-brief': {
      id: '/api/analyze-brief'
      path: '/api/analyze-brief'
      fullPath: '/api/analyze-brief'
      preLoaderRoute: typeof ApiAnalyzeBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiAnalyzeBriefRoute: ApiAnalyzeBriefRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiCheckoutConfirmRoute: ApiCheckoutConfirmRoute,
  ApiDownloadLogoRoute: ApiDownloadLogoRoute,
  ApiGenerateLogoRoute: ApiGenerateLogoRoute,
  ApiTrackRoute: ApiTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
