/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateLogoRouteImport } from './routes/api/generate-logo'
import { Route as ApiAnalyzeBriefRouteImport } from './routes/api/analyze-brief'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateLogoRoute = ApiGenerateLogoRouteImport.update({
  id: '/api/generate-logo',
  path: '/api/generate-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeBriefRoute = ApiAnalyzeBriefRouteImport.update({
  id: '/api/analyze-brief',
  path: '/api/analyze-brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-brief': typeof ApiAnalyzeBriefRoute
  '/api/generate-logo': typeof ApiGenerateLogoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-brief': typeof ApiAnalyzeBriefRoute
  '/api/generate-logo': typeof ApiGenerateLogoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-brief': typeof ApiAnalyzeBriefRoute
  '/api/generate-logo': typeof ApiGenerateLogoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacidade'
    | '/sitemap.xml'
    | '/api/analyze-brief'
    | '/api/generate-logo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidade'
    | '/sitemap.xml'
    | '/api/analyze-brief'
    | '/api/generate-logo'
  id:
    | '__root__'
    | '/'
    | '/privacidade'
    | '/sitemap.xml'
    | '/api/analyze-brief'
    | '/api/generate-logo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAnalyzeBriefRoute: typeof ApiAnalyzeBriefRoute
  ApiGenerateLogoRoute: typeof ApiGenerateLogoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-logo': {
      id: '/api/generate-logo'
      path: '/api/generate-logo'
      fullPath: '/api/generate-logo'
      preLoaderRoute: typeof ApiGenerateLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-brief': {
      id: '/api/analyze-brief'
      path: '/api/analyze-brief'
      fullPath: '/api/analyze-brief'
      preLoaderRoute: typeof ApiAnalyzeBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAnalyzeBriefRoute: ApiAnalyzeBriefRoute,
  ApiGenerateLogoRoute: ApiGenerateLogoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
